client:
  batch_size: 128
  fed_algo: FedGTA
  lr: 0.01
  momentum: 0
  num_local_epoch: 1
system:
  dataset: CIFAR10
  dirichlet_alpha: 0.01
  i_seed: 0
  model: CNN
  num_client: 10
  num_round: 100
  prox_beta: 0.5
  res_root: results
